# Reusable workflow to enable a single shared matrix for builds.
#   Only one job currently, may be extended later to include Cython builds.
on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      python-version:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  build-wheel:
    name: build-wheel
    runs-on: ${{ inputs.runner }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/bootstrap-environ
      id: bootstrap-environ
      with:
        python-version: ${{ inputs.python-version }}
        runner: ${{ inputs.runner }}
    - name: Build ${{ inputs.runner }} binaries
      run: uv build
    - name: Store dist artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ inputs.runner }}-${{ inputs.python-version }}-wheel
        path: dist
