name: Make Changelog

on:
  push:
    branches:
    - "main"

defaults:
  run:
    shell: bash

jobs:
  changelog:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.9" ]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/bootstrap-environ
      id: bootstrap-environ
      with:
        python-version: ${{ matrix.python-version }}
        runner: ${{ matrix.os }}
    - name: Update the Changelog
      run: make changelog
