name: Make Documentation

on:
  push:
    branches: ["main"]
    tags: ["*"]

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  documentation:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.x" ]
    steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ vars.RELEASE_BOT_APP_ID }}
        private-key: ${{ secrets.RELEASE_BOT_APP_PKEY }}
    - uses: actions/checkout@v4
      with:
        token: ${{ steps.app-token.outputs.token }}
    - uses: ./.github/actions/bootstrap-environ
      id: bootstrap-environ
      with:
        python-version: ${{ matrix.python-version }}
        runner: ${{ matrix.os }}
    - name: Update the Changelog
      run: |
        make changelog
        git push origin ${{ github.ref_name }}
    - name: Refresh Remotes
      run: git pull origin main && git pull origin gh-pages
    - name: Build the Docs
      run: make docs
