name: Create Tag

on:
  push:
    branches:
    - 'main'
    tags-ignore:
    - '**'

defaults:
  run:
    shell: bash

jobs:
  create-version:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.12" ]
    steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ vars.RELEASE_BOT_APP_ID }}
        private-key: ${{ secrets.RELEASE_BOT_APP_PKEY }}
    - uses: actions/checkout@v4
      with:
        token: ${{ steps.app-token.outputs.token }}
        fetch-depth: 0
        fetch-tags: true
    - uses: ./.github/actions/bootstrap-environ
      id: bootstrap-environ
      with:
        python-version: ${{ matrix.python-version }}
        runner: ${{ matrix.os }}
    # In order to make a commit, we need to initialize a user.
    - name: Initialize mandatory git config
      run: |
        git config user.name "GitHub actions"
        git config user.email noreply@github.com
    - name: Tag New Version
      run: make release-version ref=${{ github.ref_name }}
