name: Trigger Release

on:
  workflow_dispatch:
    inputs:
      level:
        description: "The level to bump the current version"
        required: true
        default: "patch"
        options:
          - "patch"
          - "minor"
          - "major"
          - "prepatch"
          - "preminor"
          - "prerelease"

jobs:
  create-version:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.9" ]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/bootstrap-environ
      id: bootstrap-environ
      with:
        python-version: ${{ matrix.python-version }}
        runner: ${{ matrix.os }}
    # In order to make a commit, we need to initialize a user.
    - name: Initialize mandatory git config
      run: |
        git config user.name "GitHub actions"
        git config user.email noreply@github.com
    - name: Tag New Version
      run: make release-version rule=${{ inputs.level }}
    - name: Push New Version
      run: git push --follow-tags origin ${{ github.ref_name}}
